### PR TITLE
fix: check elements are only non zero in read batch

### PR DESCRIPTION
**Pull request by kobigurk**

### CODE REVIEW

**Comment by jon-chuang** [comment]
Could this get merged so I can add changes?

**Review by jon-chuang — COMMENTED** [review]
Simple change

**Comment by kobigurk** [comment]
> Could this get merged so I can add changes?

You need to approve it then :joy:

**Review by jon-chuang — COMMENTED** [review]
Simple change

**Comment by kobigurk** [comment]
Yes but we have at least 1 approval policy

**Review by jon-chuang — APPROVED** [review]
much approved

**Pull request merged**
